version: '3'
services:
  app_postgres:
    container_name: risingstack_postgres
    image: "mdillon/postgis"
    ports:
      - 64000:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=risingstack_bootcamp
  app_redis:
    container_name: risingstack_redis
    image: redis:latest
    ports:
      - 64001:6379
  app:
    container_name: risingstack_node
    build: .
    volumes:
      - ./.env:/app/.env
      - ./models:/app/models
      - ./public:/app/public
      - ./scripts:/app/scripts
      - ./worker:/app/worker
      - ./web:/app/web
      - ./build:/app/build
      - ./config.js:/app/config.js
      - ./index.js:/app/index.js
      - ./docker.js:/docker.js
      - ./package.json:/app/package.json
    depends_on:
      - app_postgres
      - app_redis
    links:
      - app_postgres
      - app_redis
    ports:
      - 64002:3000 # React Development Server
      - 64003:3001 # Web API
      - 64004:5858 # Debugging port for Web API
      - 64005:3002 # Swagger Project Editor
    environment:
      PG_URI: postgres://postgres:password@app_postgres:5432/risingstack_bootcamp
      PG_USER: postgres
      PG_PASSWORD: password
      PG_DATABASE: risingstack_bootcamp
      POSTGRES_LOGGING: "true" # Logs out every query that Postgres runs through Sequelize
      RECREATE_SCHEMA: "true" # Nukes the database on every refresh
      REDIS_URI: redis://app_redis:6379
      AUTH_SAML_ENABLED: "false"
      AUTH_SALESFORCE_ENABLED: "false"
    command: ["node", "docker.js"]
    restart: always